package com.dreambotreborn.api.methods.quest.book;

public enum MiniQuest implements Quest
{
    ALFRED_GRIMHANDS_BARCRAWL, BEAR_YOUR_SOUL, CURSE_OF_THE_EMPTY_LORD,
    DADDYS_HOME, ENCHANTED_KEY, THE_ENCHANTED_KEY, ENTER_THE_ABYSS, FAMILY_PEST,
    THE_GENERALS_SHADOW, IN_SEARCH_OF_KNOWLEDGE, LAIR_OF_TARN_RAZORLOR,
    THE_MAGE_ARENA, MAGE_ARENA_I, THE_MAGE_ARENA_2, MAGE_ARENA_II,
    SKIPPY_AND_THE_MOGRES, THE_FROZEN_DOOR, HOPESPEARS_WILL, INTO_THE_TOMBS,
    HIS_FAITHFUL_SERVANTS, BARBARIAN_TRAINING;

    @Override public int getQP() { return 0; }
}
