package com.dreambotreborn.api.methods.fairyring;

/** Named fairy-ring destinations and their three-letter dial codes. */
public enum FairyLocation
{
    MUDSKIPPER_POINT("AIQ"), ISLANDS_SE_ARDOUGNE("AIR"), AUBURN_VALLEY("AIS"),
    AVIUM_SAVANNAH("AJP"), DUNGEON_DORGESHKAAN("AJQ"), KANDARIN_SLAYER_CAVE("AJR"),
    ISLAND_PENGUINS_MISCELLANIA("AJS"), NECROPOLIS("AKP"), KANDARIN_PISCATORIS("AKQ"),
    HOSIDIUS_VINERY("AKR"), FELDIP_HILLS_HUNTER("AKS"), LIGHTHOUSE("ALP"),
    MORYTANIA_HAUNTED_WOODS("ALQ"), ABYSSAL_AREA("ALR"), MCGRUBORS_WOOD("ALS"),
    ISLAND_SW_MORT_MYRE("BIP"), KALPHITE_HIVE("BIQ"), ARDOUGNE_ZOO("BIS"),
    ISLE_OF_SOULS("BJP"), FISHER_KING("BJR"), ZULANDRA("BJS"), SW_CASTLE_WARS("BKP"),
    ENCHANTED_VALLEY("BKQ"), MORT_MYRE_SWAMP("BKR"), ZANARIS("BKS"), TZHAAR("BLP"),
    LEGENDS_GUILD("BLR"), MOUNT_QUIDAMORTEM("BLS"), MISCELLANIA("CIP"),
    NW_YANILLE("CIQ"), ARCEUUS_LIBRARY("CIS"), KEBOS_LOWLANDS("CIR"),
    SINCLAIR_MANSION("CJR"), COSMIC_ENTITY_PLANE("CKP"),
    SOUTH_TAI_BWO_WANNAI_VILLAGE("CKR"), CANIFIS("CKS"), ALDARIN("CKQ"),
    ISLAND_SOUTH_DRAYNOR("CLP"), ISLAND_APE_ATOLL("CLR"), EAST_YANILLE("CLS"),
    ABYSSAL_NEXUS("DIP"), GORAKS_PLANE("DIR"), POH_SUPERIOR_GARDEN("DIQ"),
    WIZARDS_TOWER("DIS"), TOWER_OF_LIFE("DJP"), SINCLAIR_MANSION_WEST("DJR"),
    CHASM_OF_FIRE("DJR"), KARAMJA_SOUTH_MUSA_POINT("DKP"), EDGEVILLE("DKR"),
    KELDAGRIM_ENTRANCE("DKS"), NORTH_NARDAH("DLQ"), ISLAND_POISON_WASTE("DLR"),
    DUNGEON_MYRQUE_HIDEOUT("DLS");

    private final String[] code;
    FairyLocation(String code) { this.code = code.split(""); }
    public String[] getCode() { return code.clone(); }
}
